version: "3"
services:
  
  rmi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "rmi"
    restart: unless-stopped
    volumes:
      - /home/nodo/storage:/home/nodo/storage
    ports:
      - 1099:1099
    network_mode: "host"


volumes:
  rmi: {}